version: '3'

tasks:
  run: 
    cmds:
      - go run cmd/newscanoe/main.go
  build:
    cmds:
      - go build -o newscanoe cmd/newscanoe/main.go
  install:
    cmds:
      - cp ./newscanoe ~/bin/
  debug:
    cmds:
      - go run cmd/newscanoe/main.go -d 2> log
  clean:
    cmds:
      - rm ~/.cache/newscanoe/feeds.gob
