version: '3'

tasks:
  build:
    cmds:
      - go build -o newscanoe cmd/newscanoe/main.go
  install:
    cmds:
      - cp ./newscanoe ~/bin/
  debug:
    cmds:
      - go run cmd/newscanoe/main.go -d 2> log
