version: '3'

tasks:
  run: 
    cmds:
      - go run .
      
  build:
    cmds:
      - go generate ./...
      - go build -o newscanoe --ldflags="-X 'github.com/giulianopz/newscanoe/internal/app.Version=$(git describe --tags $(git rev-list --tags --max-count=1))'" .
    
  lint:
    cmds:
      - golangci-lint -v run

  install:
    cmds:
      - mkdir -p ~/bin
      - cp ./newscanoe ~/bin/

  release:
    cmds:
      - goreleaser release --debug --snapshot --skip-publish --rm-dist

  debug:
    cmds:
      - go run . -d 2> log

  clean:
    cmds:
      - rm ~/.cache/newscanoe/feeds.gob

  tag:
    cmds:
      - git tag -a {{.CLI_ARGS}} -m "Releasing version {{.CLI_ARGS}}"
