version: '3'

tasks:
  run: 
    cmds:
      - go run cmd/newscanoe/main.go
      
  build:
    cmds:
      - go generate ./...
      - go build -o newscanoe --ldflags="-X 'github.com/giulianopz/newscanoe/pkg/app.Version=$(git describe --tags $(git rev-list --tags --max-count=1))'" cmd/newscanoe/main.go
    
  lint:
    cmds:
      - golangci-lint -v run

  install:
    cmds:
      - mkdir -p ~/bin
      - cp ./newscanoe ~/bin/

  release:
    cmds:
      - goreleaser release --debug --snapshot --skip-publish --rm-dist

  debug:
    cmds:
      - go run cmd/newscanoe/main.go -d 2> log

  clean:
    cmds:
      - rm ~/.cache/newscanoe/feeds.gob
