feeds:
    - name: <antirez>
      url: http://antirez.com/rss
    - name: Andreas Kling
      url: https://awesomekling.github.io/feed.xml
    - name: Andrej Karpathy blog
      url: https://karpathy.github.io/feed.xml
    - name: Beej's Bit Bucket
      url: https://beej.us/blog/rss.xml
    - name: Bits from Debian
      url: https://bits.debian.org/feeds/feed.rss
    - name: Browsertech Digest
      url: https://digest.browsertech.com/rss
    - name: Coding Horror
      url: https://blog.codinghorror.com/rss/
    - name: DaedTech
      url: https://feeds.feedblitz.com/daedtech/www
    - name: Dave Cheney
      url: http://dave.cheney.net/feed
    - name: Drew DeVault's blog
      url: https://drewdevault.com/blog/index.xml
    - name: Eli Bendersky's website
      url: https://eli.thegreenplace.net/feeds/all.atom.xml
    - name: Explained from First Principles
      url: https://explained-from-first-principles.com/feed.xml
    - name: Fabien Sanglard
      url: https://fabiensanglard.net/rss.xml
    - name: Faultlore
      url: https://faultlore.com/blah/rss.xml
    - name: Fernando Borretti
      url: https://borretti.me/feed.xml
    - name: Figma Blog | Shortcut
      url: https://www.figma.com/blog/feed/atom.xml
    - name: Golang Weekly
      url: https://golangweekly.com/rss/
    - name: Hackaday
      url: https://hackaday.com/feed/
    - name: Hacker News
      url: https://news.ycombinator.com/rss
    - name: Hillel Wayne
      url: https://www.hillelwayne.com/index.xml
    - name: Ivan on Containers, Kubernetes, and Server-Side
      url: https://iximiuz.com/feed.rss
    - name: Joel on Software
      url: https://www.joelonsoftware.com/feed/
    - name: Jon Skeet's coding blog
      url: https://codeblog.jonskeet.uk/feed/
    - name: Julia Evans
      url: https://jvns.ca/atom.xml
    - name: LOW←TECH MAGAZINE English
      url: https://solar.lowtechmagazine.com/feeds/all-en.atom.xml
    - name: LWN.net
      url: https://lwn.net/headlines/newrss
    - name: Linux Journal - The Original Magazine of the Linux Community
      url: https://www.linuxjournal.com/node/feed
    - name: 'Lobsters: programming - Use when every tag or no specific tag applies'
      url: https://lobste.rs/t/programming.rss
    - name: Loris Cro's Personal Website
      url: https://kristoff.it/index.xml
    - name: Mara's Blog
      url: https://blog.m-ou.se/index.xml
    - name: Martin Fowler
      url: https://martinfowler.com/feed.atom
    - name: Martin Haspelmath - Diversity Linguistics Comment
      url: https://dlc.hypotheses.org/author/dlc/rss
    - name: Math ∩ Programming
      url: https://jeremykun.com/feed/
    - name: Matt Might's blog
      url: https://matt.might.net/articles/feed.rss
    - name: Mitchell Hashimoto
      url: https://mitchellh.com/feed.xml
    - name: Netflix TechBlog - Medium
      url: https://netflixtechblog.com/feed
    - name: Peter Norvig
      url: http://www.norvig.com/rss-feed.xml
    - name: Posts on Made of Bugs
      url: https://blog.nelhage.com/atom.xml
    - name: Programming With Style
      url: https://programmingwithstyle.com/index.xml
    - name: Random ASCII - tech blog of Bruce Dawson
      url: https://randomascii.wordpress.com/rss
    - name: Ratfactor Feed
      url: http://ratfactor.com/atom.xml
    - name: Register Spill
      url: https://registerspill.thorstenball.com/feed
    - name: Saveitforparts
      url: https://saveitforparts.wordpress.com/rss
    - name: Schneier on Security
      url: https://www.schneier.com/feed/atom
    - name: Scott Hanselman's Blog
      url: http://feeds.hanselman.com/ScottHanselman
    - name: Simon Willison's Weblog
      url: https://simonwillison.net/atom/everything/
    - name: 'Simon Willison''s Weblog: Entries'
      url: https://simonwillison.net/atom/entries/
    - name: Stephen Wolfram Writings
      url: https://writings.stephenwolfram.com/feed/
    - name: Steve's blog
      url: https://blog.einval.com/index.rss
    - name: Techdirt
      url: https://www.techdirt.com/feed/
    - name: The Clean Code Blog
      url: http://blog.cleancoder.com/atom
    - name: The Cloudflare Blog
      url: https://blog.cloudflare.com/rss/
    - name: The Fly Blog
      url: https://fly.io/blog/feed.xml
    - name: The Go Blog
      url: http://blog.golang.org/feed.atom
    - name: The Observation Deck
      url: http://dtrace.org/blogs/bmc/feed/
    - name: The Pragmatic Engineer
      url: https://blog.pragmaticengineer.com/rss/
    - name: The Software Freedom Conservancy
      url: https://sfconservancy.org/feeds/omnibus
    - name: The Technium
      url: https://feedpress.me/TheTechnium
    - name: absorptions
      url: https://www.windytan.com/feeds/posts/default
    - name: bunnie's blog
      url: https://www.bunniestudios.com/blog/?feed=rss
    - name: daniel.haxx.se
      url: https://daniel.haxx.se/blog/feed/
    - name: doubleagent.net
      url: https://doubleagent.net/feed.xml
    - name: fasterthanli.me
      url: https://fasterthanli.me/index.xml
    - name: journal.stuffwithstuff.com
      url: https://journal.stuffwithstuff.com/rss.xml
    - name: jwz
      url: https://www.jwz.org/blog/rss
    - name: null program
      url: https://nullprogram.com/feed/
    - name: rakyll.org
      url: https://rakyll.org/index.xml
    - name: research!rsc
      url: https://research.swtch.com/feed.atom
    - name: see shy jo
      url: https://joeyh.name/blog/index.rss
    - name: ★❤✰ Vicki Boykis ★❤✰
      url: https://vickiboykis.com/index.xml
    - name: Language Log
      url: https://languagelog.ldc.upenn.edu/nll/?feed=rss2
    - name: Wellformedness
      url: https://www.wellformedness.com/blog/rss
    - name: outdex
      url: https://outde.xyz/feeds/all.atom.xml
    - name: Stories by Yoav Goldberg on Medium
      url: https://medium.com/feed/@yoav.goldberg
    - name: etcetera
      url: https://giuliomagnifico.blog/feed.xml
    - name: Underjord.io
      url: https://underjord.io/feed.xml
    - name: The Ed's Up
      url: https://buttondown.email/edyong209/rss
    - name: Recent Gists from yoavg
      url: https://gist.github.com/yoavg.atom
    - name: Casey Muratori's Blog
      url: https://caseymuratori.com/blog_atom.rss
    - name: David Heinemeier Hansson
      url: https://world.hey.com/dhh/feed.atom
    - name: Project Zero
      url: https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss
    - name: Jack Rusher's Internet Homestead
      url: https://jackrusher.com/feed.xml
    - name: Martin Kleppmann's blog
      url: http://feeds.feedburner.com/martinkl
    - name: Neil with Data
      url: https://www.neilwithdata.com/feeds/all.atom.xml
